/*
 * ESP32 Gesture Recognition Inference
 * Author: Qoder
 * Date: 2025
 * 
 * This code runs gesture recognition on ESP32 using TensorFlow Lite Micro.
 * It reads sEMG data from 12 channels and classifies gestures in real-time.
 */

#include <Arduino.h>
#include <TensorFlowLite.h>
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"

// Include the model (generated by train_model.py)
#include "model.h"

// ============== Configuration ==============
#define NUM_CHANNELS 12
#define WINDOW_SIZE 200      // 100ms at 2000Hz sampling
#define STEP_SIZE 100        // 50% overlap
#define NUM_FEATURES 6       // MAV, RMS, WL, ZC, SSC, VAR per channel
#define INPUT_SIZE (NUM_CHANNELS * NUM_FEATURES)  // 72
#define NUM_CLASSES 3
#define SAMPLING_RATE 2000   // Hz

// EMG input pins (adjust according to your hardware)
const int emgPins[NUM_CHANNELS] = {
  34, 35, 32, 33, 25, 26,  // First 6 channels
  27, 14, 12, 13, 4, 2      // Last 6 channels
};

// ============== TensorFlow Lite Globals ==============
// Tensor arena size (adjust based on model size)
constexpr int kTensorArenaSize = 20 * 1024;
alignas(16) uint8_t tensor_arena[kTensorArenaSize];

const tflite::Model* model = nullptr;
tflite::MicroInterpreter* interpreter = nullptr;
TfLiteTensor* input_tensor = nullptr;
TfLiteTensor* output_tensor = nullptr;

// ============== EMG Data Buffer ==============
float emgBuffer[WINDOW_SIZE][NUM_CHANNELS];
int bufferIndex = 0;
bool bufferFull = false;

// ============== Filter Coefficients ==============
// Simple high-pass filter coefficients (10Hz cutoff at 2000Hz)
// y[n] = b0*x[n] + b1*x[n-1] - a1*y[n-1]
const float HP_B0 = 0.9844f;
const float HP_B1 = -0.9844f;
const float HP_A1 = -0.9689f;

// Filter state for each channel
float filterState[NUM_CHANNELS][2] = {0};  // [x[n-1], y[n-1]]

// ============== Function Prototypes ==============
void setupTFLite();
float applyHighPassFilter(float input, int channel);
void processEMGSample();
void extractFeatures(float* features);
float computeMAV(float* data, int len);
float computeRMS(float* data, int len);
float computeWL(float* data, int len);
int computeZC(float* data, int len);
int computeSSC(float* data, int len);
float computeVariance(float* data, int len);
int classifyGesture();
void printGesture(int gesture);

// ============== Setup ==============
void setup() {
  Serial.begin(115200);
  delay(1000);
  
  Serial.println("========================================");
  Serial.println("ESP32 Gesture Recognition System");
  Serial.println("========================================");
  
  // Initialize EMG pins
  for (int i = 0; i < NUM_CHANNELS; i++) {
    pinMode(emgPins[i], INPUT);
  }
  
  // Initialize TensorFlow Lite
  setupTFLite();
  
  Serial.println("System ready!");
  Serial.println("Waiting for EMG data...");
  Serial.println("----------------------------------------\n");
}

// ============== Main Loop ==============
void loop() {
  // Read EMG samples at ~2000Hz
  static unsigned long lastSampleTime = 0;
  unsigned long currentTime = micros();
  
  // Sample every 500 microseconds (2000Hz)
  if (currentTime - lastSampleTime >= 500) {
    lastSampleTime = currentTime;
    
    // Read and process one sample from all channels
    processEMGSample();
    
    // When buffer is full, extract features and classify
    if (bufferFull) {
      int gesture = classifyGesture();
      printGesture(gesture);
      
      // Slide window (keep 50% overlap)
      // Move second half to first half
      for (int i = 0; i < STEP_SIZE; i++) {
        for (int ch = 0; ch < NUM_CHANNELS; ch++) {
          emgBuffer[i][ch] = emgBuffer[i + STEP_SIZE][ch];
        }
      }
      bufferIndex = STEP_SIZE;
      bufferFull = false;
    }
  }
}

// ============== TensorFlow Lite Setup ==============
void setupTFLite() {
  Serial.println("Initializing TensorFlow Lite...");
  
  // Load model
  model = tflite::GetModel(gesture_model);
  
  if (model->version() != TFLITE_SCHEMA_VERSION) {
    Serial.println("Model schema version mismatch!");
    return;
  }
  
  // Create resolver with required operations
  static tflite::MicroMutableOpResolver<10> resolver;
  resolver.AddFullyConnected();
  resolver.AddRelu();
  resolver.AddSoftmax();
  resolver.AddQuantize();
  resolver.AddDequantize();
  resolver.AddReshape();
  resolver.AddAdd();
  resolver.AddMul();
  resolver.AddBatchNorm();
  resolver.AddLogistic();
  
  // Create interpreter
  static tflite::MicroInterpreter static_interpreter(
    model, resolver, tensor_arena, kTensorArenaSize);
  interpreter = &static_interpreter;
  
  // Allocate tensors
  TfLiteStatus allocate_status = interpreter->AllocateTensors();
  if (allocate_status != kTfLiteOk) {
    Serial.println("Failed to allocate tensors!");
    return;
  }
  
  // Get input and output tensors
  input_tensor = interpreter->input(0);
  output_tensor = interpreter->output(0);
  
  Serial.println("TensorFlow Lite initialized successfully!");
  Serial.print("Input size: ");
  Serial.println(input_tensor->dims->data[1]);
  Serial.print("Output size: ");
  Serial.println(output_tensor->dims->data[1]);
}

// ============== EMG Processing ==============
float applyHighPassFilter(float input, int channel) {
  // Apply simple high-pass filter to remove DC offset
  float x_n = input;
  float x_n1 = filterState[channel][0];
  float y_n1 = filterState[channel][1];
  
  float y_n = HP_B0 * x_n + HP_B1 * x_n1 - HP_A1 * y_n1;
  
  // Update state
  filterState[channel][0] = x_n;
  filterState[channel][1] = y_n;
  
  return y_n;
}

void processEMGSample() {
  // Read all channels
  for (int ch = 0; ch < NUM_CHANNELS; ch++) {
    // Read ADC value (12-bit: 0-4095)
    int rawValue = analogRead(emgPins[ch]);
    
    // Convert to voltage (assuming 3.3V reference)
    float voltage = (rawValue / 4095.0f) * 3.3f - 1.65f;  // Center at 0
    
    // Apply high-pass filter
    float filtered = applyHighPassFilter(voltage, ch);
    
    // Store in buffer
    emgBuffer[bufferIndex][ch] = filtered;
  }
  
  bufferIndex++;
  
  if (bufferIndex >= WINDOW_SIZE) {
    bufferFull = true;
    bufferIndex = WINDOW_SIZE;  // Keep at max until processed
  }
}

// ============== Feature Extraction ==============
float computeMAV(float* data, int len) {
  float sum = 0;
  for (int i = 0; i < len; i++) {
    sum += abs(data[i]);
  }
  return sum / len;
}

float computeRMS(float* data, int len) {
  float sum = 0;
  for (int i = 0; i < len; i++) {
    sum += data[i] * data[i];
  }
  return sqrt(sum / len);
}

float computeWL(float* data, int len) {
  float wl = 0;
  for (int i = 1; i < len; i++) {
    wl += abs(data[i] - data[i-1]);
  }
  return wl;
}

int computeZC(float* data, int len) {
  int zc = 0;
  for (int i = 1; i < len; i++) {
    if ((data[i] * data[i-1]) < 0) {
      zc++;
    }
  }
  return zc;
}

int computeSSC(float* data, int len) {
  int ssc = 0;
  for (int i = 2; i < len; i++) {
    float diff1 = data[i-1] - data[i-2];
    float diff2 = data[i] - data[i-1];
    if ((diff1 * diff2) < 0) {
      ssc++;
    }
  }
  return ssc;
}

float computeVariance(float* data, int len) {
  float mean = 0;
  for (int i = 0; i < len; i++) {
    mean += data[i];
  }
  mean /= len;
  
  float var = 0;
  for (int i = 0; i < len; i++) {
    float diff = data[i] - mean;
    var += diff * diff;
  }
  return var / len;
}

void extractFeatures(float* features) {
  // Temporary array for one channel
  float channelData[WINDOW_SIZE];
  
  int featIdx = 0;
  
  for (int ch = 0; ch < NUM_CHANNELS; ch++) {
    // Extract channel data
    for (int i = 0; i < WINDOW_SIZE; i++) {
      channelData[i] = emgBuffer[i][ch];
    }
    
    // Compute features
    features[featIdx++] = computeMAV(channelData, WINDOW_SIZE);
    features[featIdx++] = computeRMS(channelData, WINDOW_SIZE);
    features[featIdx++] = computeWL(channelData, WINDOW_SIZE);
    features[featIdx++] = (float)computeZC(channelData, WINDOW_SIZE);
    features[featIdx++] = (float)computeSSC(channelData, WINDOW_SIZE);
    features[featIdx++] = computeVariance(channelData, WINDOW_SIZE);
  }
}

// ============== Classification ==============
int classifyGesture() {
  // Extract features
  float features[INPUT_SIZE];
  extractFeatures(features);
  
  // Normalize features (using pre-computed mean and std from training)
  // These values should be updated based on your training data statistics
  // For now, using approximate values - replace with actual training stats
  const float mean[INPUT_SIZE] = {0.0f};  // Update with training data mean
  const float std[INPUT_SIZE] = {1.0f};   // Update with training data std
  
  for (int i = 0; i < INPUT_SIZE; i++) {
    features[i] = (features[i] - mean[i]) / std[i];
  }
  
  // Copy to input tensor
  for (int i = 0; i < INPUT_SIZE; i++) {
    input_tensor->data.f[i] = features[i];
  }
  
  // Run inference
  TfLiteStatus invoke_status = interpreter->Invoke();
  if (invoke_status != kTfLiteOk) {
    Serial.println("Inference failed!");
    return -1;
  }
  
  // Get output
  float maxProb = 0;
  int predictedClass = 0;
  
  for (int i = 0; i < NUM_CLASSES; i++) {
    float prob = output_tensor->data.f[i];
    if (prob > maxProb) {
      maxProb = prob;
      predictedClass = i;
    }
  }
  
  return predictedClass;
}

void printGesture(int gesture) {
  const char* gestureNames[] = {"Gesture 0", "Gesture 1", "Gesture 2"};
  
  Serial.print("Detected: ");
  Serial.print(gestureNames[gesture]);
  Serial.print(" (Confidence: ");
  
  // Print confidence
  float maxProb = 0;
  for (int i = 0; i < NUM_CLASSES; i++) {
    float prob = output_tensor->data.f[i];
    if (prob > maxProb) maxProb = prob;
  }
  Serial.print(maxProb * 100, 1);
  Serial.println("%)");
}

// ============== Alternative: Simple Threshold-Based Classification ==============
// If TFLite is too heavy, use this simple implementation
/*
int classifyGestureSimple() {
  float features[INPUT_SIZE];
  extractFeatures(features);
  
  // Simple threshold-based classification
  // Replace with your trained thresholds
  float threshold1 = 0.5f;
  float threshold2 = 1.0f;
  
  float avgMAV = 0;
  for (int i = 0; i < NUM_CHANNELS; i++) {
    avgMAV += features[i * NUM_FEATURES];  // MAV is first feature
  }
  avgMAV /= NUM_CHANNELS;
  
  if (avgMAV < threshold1) return 0;
  else if (avgMAV < threshold2) return 1;
  else return 2;
}
*/
