"""
Export Trained Model Weights for ESP32
Author: Qoder
Date: 2025

This script exports trained model weights in C array format
for embedding in ESP32 Arduino code.
"""

import numpy as np
import json
import os


def export_weights_to_c(model_weights_path, output_path):
    """
    Convert numpy weights to C header file format.
    
    Args:
        model_weights_path: Path to model_weights.npz
        output_path: Path to output .h file
    """
    
    print(f"Loading weights from: {model_weights_path}")
    weights = np.load(model_weights_path)
    
    with open(output_path, 'w') as f:
        f.write("/*\n")
        f.write(" * Trained Model Weights for ESP32\n")
        f.write(" * Auto-generated by export_weights.py\n")
        f.write(" * DO NOT EDIT MANUALLY\n")
        f.write(" */\n\n")
        f.write("#ifndef MODEL_WEIGHTS_H\n")
        f.write("#define MODEL_WEIGHTS_H\n\n")
        
        # Export each layer's weights
        layer_idx = 0
        while f'layer_{layer_idx}_weights' in weights:
            w_key = f'layer_{layer_idx}_weights'
            b_key = f'layer_{layer_idx}_bias'
            
            W = weights[w_key]
            b = weights[b_key]
            
            print(f"Layer {layer_idx}: {W.shape} -> {b.shape}")
            
            # Export weights
            f.write(f"// Layer {layer_idx} weights: {W.shape[0]} x {W.shape[1]}\n")
            f.write(f"const double W{layer_idx + 1}[] = {{\n  ")
            
            flat_w = W.flatten()
            for i, val in enumerate(flat_w):
                if i > 0:
                    if i % 8 == 0:
                        f.write(",\n  ")
                    else:
                        f.write(", ")
                f.write(f"{val:.10f}")
            
            f.write("\n};\n\n")
            
            # Export biases
            f.write(f"// Layer {layer_idx} biases: {b.shape[0]}\n")
            f.write(f"const double b{layer_idx + 1}[] = {{\n  ")
            
            for i, val in enumerate(b):
                if i > 0:
                    if i % 8 == 0:
                        f.write(",\n  ")
                    else:
                        f.write(", ")
                f.write(f"{val:.10f}")
            
            f.write("\n};\n\n")
            
            layer_idx += 1
        
        f.write("#endif // MODEL_WEIGHTS_H\n")
    
    print(f"\nWeights exported to: {output_path}")


def export_normalization_params(data_path, output_path):
    """
    Export feature normalization parameters (mean and std) for ESP32.
    
    Args:
        data_path: Path to preprocessed_data.pkl
        output_path: Path to output .h file
    """
    import pickle
    
    print(f"\nLoading data from: {data_path}")
    with open(data_path, 'rb') as f:
        data = pickle.load(f)
    
    X_train = data['X_train']
    
    # Calculate mean and std
    mean = np.mean(X_train, axis=0)
    std = np.std(X_train, axis=0)
    
    # Avoid division by zero
    std[std == 0] = 1.0
    
    print(f"Feature mean shape: {mean.shape}")
    print(f"Feature std shape: {std.shape}")
    
    with open(output_path, 'w') as f:
        f.write("/*\n")
        f.write(" * Feature Normalization Parameters\n")
        f.write(" * Auto-generated by export_weights.py\n")
        f.write(" */\n\n")
        f.write("#ifndef NORMALIZATION_PARAMS_H\n")
        f.write("#define NORMALIZATION_PARAMS_H\n\n")
        f.write(f"#define INPUT_SIZE {len(mean)}\n\n")
        
        # Export mean
        f.write("const double featureMean[INPUT_SIZE] = {\n  ")
        for i, val in enumerate(mean):
            if i > 0:
                if i % 8 == 0:
                    f.write(",\n  ")
                else:
                    f.write(", ")
            f.write(f"{val:.10f}")
        f.write("\n};\n\n")
        
        # Export std
        f.write("const double featureStd[INPUT_SIZE] = {\n  ")
        for i, val in enumerate(std):
            if i > 0:
                if i % 8 == 0:
                    f.write(",\n  ")
                else:
                    f.write(", ")
            f.write(f"{val:.10f}")
        f.write("\n};\n\n")
        
        f.write("#endif // NORMALIZATION_PARAMS_H\n")
    
    print(f"Normalization params exported to: {output_path}")


def export_model_info(data_path, output_path):
    """
    Export model architecture information.
    """
    import pickle
    
    with open(data_path, 'rb') as f:
        data = pickle.load(f)
    
    info = {
        'num_channels': data.get('num_channels', 12),
        'window_size': data.get('window_size', 200),
        'sampling_rate': data.get('sampling_rate', 2000),
        'num_features': 6,
        'input_size': data['X_train'].shape[1],
        'num_classes': len(np.unique(data['y_train'])),
        'feature_names': data.get('feature_names', [])
    }
    
    with open(output_path, 'w') as f:
        json.dump(info, f, indent=2)
    
    print(f"\nModel info exported to: {output_path}")
    print(json.dumps(info, indent=2))


def main(output_dir=None):
    """Main export function.
    
    Args:
        output_dir: Output directory for exported files.
                    If None, uses the script's own directory.
    """
    if output_dir is None:
        output_dir = os.path.dirname(__file__)
    os.makedirs(output_dir, exist_ok=True)
    
    # Export weights
    weights_path = os.path.join(output_dir, 'model_weights.npz')
    if os.path.exists(weights_path):
        weights_output = os.path.join(output_dir, 'model_weights.h')
        export_weights_to_c(weights_path, weights_output)
    else:
        print(f"Warning: {weights_path} not found. Train model first.")
    
    # Export normalization params
    data_path = os.path.join(output_dir, 'preprocessed_data.pkl')
    if os.path.exists(data_path):
        norm_output = os.path.join(output_dir, 'normalization_params.h')
        export_normalization_params(data_path, norm_output)
        
        # Export model info
        info_output = os.path.join(output_dir, 'model_info.json')
        export_model_info(data_path, info_output)
    else:
        print(f"Warning: {data_path} not found. Run preprocessing first.")
    
    print("\n" + "="*50)
    print("Export complete!")
    print("="*50)


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='Export model weights for ESP32')
    parser.add_argument('--output-dir', type=str, default=None,
                        help='Output directory for exported files')
    args = parser.parse_args()
    main(output_dir=args.output_dir)
